baseURL = "http://dejaq.io/"
languageCode = "en-us"
title = "DejaQ"
theme = "hyde"
googleanalytics = "UA-147978251-1"

[params]
    description = "The public official website for DejaQ"
    logo = "dejaq-logo1-white.png"