baseURL = "https://dejaq.io/"
languageCode = "en-us"
title = "DejaQ"
theme = "hyde"
googleanalytics = "UA-147978251-1"

[params]
    description = "The official DejaQ website"
    logo = "dejaq-logo1-white.png"